/*
 * Copyright (c) 2005 The Regents of The University of Michigan
 * Copyright (c) 2007 MIPS Technologies, Inc.
 * Copyright (c) 2016 The University of Virginia
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met: redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer;
 * redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution;
 * neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Authors: Gabe Black
 *          Korey Sewell
 *          Alec Roelke
 */

#include "arch/riscv/linux/process.hh"

#include <map>

#include "arch/riscv/isa_traits.hh"
#include "arch/riscv/linux/linux.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "debug/SyscallVerbose.hh"
#include "kern/linux/linux.hh"
#include "sim/eventq.hh"
#include "sim/process.hh"
#include "sim/syscall_desc.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"

using namespace std;
using namespace RiscvISA;

/// Target uname() handler.
static SyscallReturn
uname32Func(SyscallDesc *desc, int callnum, Process *process,
          ThreadContext *tc)
{
    int index = 0;
    TypedBufferArg<Linux::utsname> name(process->getSyscallArg(tc, index));

    strcpy(name->sysname, "Linux");
    strcpy(name->nodename,"sim.gem5.org");
    strcpy(name->release, "3.0.0");
    strcpy(name->version, "#1 Mon Aug 18 11:32:15 EDT 2003");
    strcpy(name->machine, "riscv32");

    name.copyOut(tc->getMemProxy());
    return 0;
}

/// Target uname() handler.
static SyscallReturn
uname64Func(SyscallDesc *desc, int callnum, Process *process,
          ThreadContext *tc)
{
    int index = 0;
    TypedBufferArg<Linux::utsname> name(process->getSyscallArg(tc, index));

    strcpy(name->sysname, "Linux");
    strcpy(name->nodename,"sim.gem5.org");
    strcpy(name->release, "3.0.0");
    strcpy(name->version, "#1 Mon Aug 18 11:32:15 EDT 2003");
    strcpy(name->machine, "riscv64");

    name.copyOut(tc->getMemProxy());
    return 0;
}

std::map<int, SyscallDesc> Riscv32LinuxProcess::syscallDescs = {
    {0,   SyscallDesc("syscall", unimplementedFunc)},
    {1,   SyscallDesc("exit", exitFunc)},
    {2,   SyscallDesc("fork", unimplementedFunc)},
    {3,   SyscallDesc("read", readFunc)},
    {4,   SyscallDesc("write", writeFunc)},
    {5,   SyscallDesc("open", openFunc<Riscv64Linux>)},
    {6,   SyscallDesc("close", closeFunc)},
    {7,   SyscallDesc("unused#7", unimplementedFunc)},
    {8,   SyscallDesc("creat", unimplementedFunc)},
    {9,   SyscallDesc("link", unimplementedFunc)},
    {10,  SyscallDesc("unlink", unlinkFunc)},
    {11,  SyscallDesc("execve", unimplementedFunc)},
    {12,  SyscallDesc("chdir", unimplementedFunc)},
    {13,  SyscallDesc("time", timeFunc<Riscv64Linux>)},
    {14,  SyscallDesc("mknod", unimplementedFunc)},
    {15,  SyscallDesc("chmod", chmodFunc<Riscv64Linux>)},
    {16,  SyscallDesc("lchown", chownFunc)},
    {17,  SyscallDesc("unused#17", unimplementedFunc)},
    {18,  SyscallDesc("unused#18", unimplementedFunc)},
    {19,  SyscallDesc("lseek", lseekFunc)},
    {20,  SyscallDesc("getpid", getpidFunc)},
    {21,  SyscallDesc("mount", unimplementedFunc)},
    {22,  SyscallDesc("umount", unimplementedFunc)},
    {23,  SyscallDesc("setuid", setuidFunc)},
    {24,  SyscallDesc("getuid", getuidFunc)},
    {25,  SyscallDesc("stime", unimplementedFunc)},
    {26,  SyscallDesc("ptrace", unimplementedFunc)},
    {27,  SyscallDesc("alarm", unimplementedFunc)},
    {28,  SyscallDesc("unused#28", unimplementedFunc)},
    {29,  SyscallDesc("pause", unimplementedFunc)},
    {30,  SyscallDesc("utime", unimplementedFunc)},
    {31,  SyscallDesc("unused#31", unimplementedFunc)},
    {32,  SyscallDesc("unused#32", unimplementedFunc)},
    {33,  SyscallDesc("access", accessFunc)},
    {34,  SyscallDesc("nice", unimplementedFunc)},
    {35,  SyscallDesc("unused#35", unimplementedFunc)},
    {36,  SyscallDesc("sync", unimplementedFunc)},
    {37,  SyscallDesc("kill", ignoreFunc)},
    {38,  SyscallDesc("rename", renameFunc)},
    {39,  SyscallDesc("mkdir", mkdirFunc)},
    {40,  SyscallDesc("rmdir", unimplementedFunc)},
    {41,  SyscallDesc("dup", dupFunc)},
    {42,  SyscallDesc("pipe", pipePseudoFunc)},
    {43,  SyscallDesc("times", timesFunc<Riscv64Linux>)},
    {44,  SyscallDesc("unused#44", unimplementedFunc)},
    {45,  SyscallDesc("brk", brkFunc)},
    {46,  SyscallDesc("setgid", unimplementedFunc)},
    {47,  SyscallDesc("getgid", getgidFunc)},
    {48,  SyscallDesc("unused#48", unimplementedFunc)},
    {49,  SyscallDesc("geteuid", geteuidFunc)},
    {50,  SyscallDesc("getegid", getegidFunc)},
    {51,  SyscallDesc("acct", unimplementedFunc)},
    {52,  SyscallDesc("umount2", unimplementedFunc)},
    {53,  SyscallDesc("unused#53", unimplementedFunc)},
    {54,  SyscallDesc("ioctl", ioctlFunc<Riscv64Linux>)},
    {55,  SyscallDesc("fcntl", fcntlFunc)},
    {56,  SyscallDesc("unused#56", unimplementedFunc)},
    {57,  SyscallDesc("setpgid", unimplementedFunc)},
    {58,  SyscallDesc("unused#58", unimplementedFunc)},
    {59,  SyscallDesc("unused#59", unimplementedFunc)},
    {60,  SyscallDesc("umask", umaskFunc)},
    {61,  SyscallDesc("chroot", unimplementedFunc)},
    {62,  SyscallDesc("ustat", unimplementedFunc)},
    {63,  SyscallDesc("dup2", unimplementedFunc)},
    {64,  SyscallDesc("getppid", getppidFunc)},
    {65,  SyscallDesc("getpgrp", unimplementedFunc)},
    {66,  SyscallDesc("setsid", unimplementedFunc)},
    {67,  SyscallDesc("sigaction",unimplementedFunc)},
    {68,  SyscallDesc("unused#68", unimplementedFunc)},
    {69,  SyscallDesc("unused#69", unimplementedFunc)},
    {70,  SyscallDesc("setreuid", unimplementedFunc)},
    {71,  SyscallDesc("setregid", unimplementedFunc)},
    {72,  SyscallDesc("sigsuspend", unimplementedFunc)},
    {73,  SyscallDesc("sigpending", unimplementedFunc)},
    {74,  SyscallDesc("sethostname", ignoreFunc)},
    {75,  SyscallDesc("setrlimit", ignoreFunc)},
    {76,  SyscallDesc("getrlimit", getrlimitFunc<Riscv64Linux>)},
    {77,  SyscallDesc("getrusage", getrusageFunc<Riscv64Linux>)},
    {78,  SyscallDesc("gettimeofday", gettimeofdayFunc<Riscv64Linux>)},
    {79,  SyscallDesc("settimeofday", unimplementedFunc)},
    {80,  SyscallDesc("getgroups", unimplementedFunc)},
    {81,  SyscallDesc("setgroups", unimplementedFunc)},
    {82,  SyscallDesc("reserved#82", unimplementedFunc)},
    {83,  SyscallDesc("symlink", unimplementedFunc)},
    {84,  SyscallDesc("unused#84", unimplementedFunc)},
    {85,  SyscallDesc("readlink", readlinkFunc)},
    {86,  SyscallDesc("uselib", unimplementedFunc)},
    {87,  SyscallDesc("swapon", unimplementedFunc)},
    {88,  SyscallDesc("reboot", unimplementedFunc)},
    {89,  SyscallDesc("readdir", unimplementedFunc)},
    {90,  SyscallDesc("mmap", mmapFunc<Riscv64Linux>)},
    {91,  SyscallDesc("munmap", munmapFunc)},
    {92,  SyscallDesc("truncate", truncateFunc)},
    {93,  SyscallDesc("ftruncate", ftruncateFunc)},
    {94,  SyscallDesc("fchmod", unimplementedFunc)},
    {95,  SyscallDesc("fchown", unimplementedFunc)},
    {96,  SyscallDesc("getpriority", unimplementedFunc)},
    {97,  SyscallDesc("setpriority", unimplementedFunc)},
    {98,  SyscallDesc("unused#98", unimplementedFunc)},
    {99,  SyscallDesc("statfs", unimplementedFunc)},
    {100,  SyscallDesc("fstatfs", unimplementedFunc)},
    {101,  SyscallDesc("unused#101", unimplementedFunc)},
    {102,  SyscallDesc("socketcall", unimplementedFunc)},
    {103,  SyscallDesc("syslog", unimplementedFunc)},
    {104,  SyscallDesc("setitimer", unimplementedFunc)},
    {105,  SyscallDesc("getitimer", unimplementedFunc)},
    {106,  SyscallDesc("stat",  statFunc<Riscv64Linux>)},
    {107,  SyscallDesc("lstat", unimplementedFunc)},
    {108,  SyscallDesc("fstat", fstatFunc<Riscv64Linux>)},
    {109,  SyscallDesc("unused#109", unimplementedFunc)},
    {110,  SyscallDesc("unused#101", unimplementedFunc)},
    {111,  SyscallDesc("vhangup", unimplementedFunc)},
    {112,  SyscallDesc("unused#112", unimplementedFunc)},
    {113,  SyscallDesc("syscall", unimplementedFunc)},
    {114,  SyscallDesc("wait4", unimplementedFunc)},
    {115,  SyscallDesc("swapoff", unimplementedFunc)},
    {116,  SyscallDesc("sysinfo", sysinfoFunc<Riscv64Linux>)},
    {117,  SyscallDesc("ipc", unimplementedFunc)},
    {118,  SyscallDesc("fsync", unimplementedFunc)},
    {119,  SyscallDesc("sigreturn", unimplementedFunc)},
    {120,  SyscallDesc("clone", cloneFunc<Riscv64Linux>)},
    {121,  SyscallDesc("setdomainname", unimplementedFunc)},
    {122,  SyscallDesc("uname", uname32Func)},
    {123,  SyscallDesc("unused#123", unimplementedFunc)},
    {124,  SyscallDesc("adjtimex", unimplementedFunc)},
    {125,  SyscallDesc("mprotect", ignoreFunc)},
    {126,  SyscallDesc("sigprocmask", ignoreFunc, SyscallDesc::WarnOnce)},
    {127,  SyscallDesc("unused#127", unimplementedFunc)},
    {128,  SyscallDesc("init_module", unimplementedFunc)},
    {129,  SyscallDesc("delete_module", unimplementedFunc)},
    {130,  SyscallDesc("unused#130", unimplementedFunc)},
    {131,  SyscallDesc("quotactl", unimplementedFunc)},
    {132,  SyscallDesc("getpgid", unimplementedFunc)},
    {133,  SyscallDesc("fchdir", unimplementedFunc)},
    {134,  SyscallDesc("bdflush", unimplementedFunc)},
    {135,  SyscallDesc("sysfs", unimplementedFunc)},
    {136,  SyscallDesc("personality", unimplementedFunc)},
    {137,  SyscallDesc("reserved#138", unimplementedFunc)},
    {138,  SyscallDesc("setfsuid", unimplementedFunc)},
    {139,  SyscallDesc("setfsgid", unimplementedFunc)},
    {140,  SyscallDesc("llseek", _llseekFunc)},
    {141,  SyscallDesc("getdents", unimplementedFunc)},
    {142,  SyscallDesc("newselect", unimplementedFunc)},
    {143,  SyscallDesc("flock", unimplementedFunc)},
    {144,  SyscallDesc("msync", unimplementedFunc)},
    {145,  SyscallDesc("readv", unimplementedFunc)},
    {146,  SyscallDesc("writev", writevFunc<Riscv64Linux>)},
    {147,  SyscallDesc("getsid", unimplementedFunc)},
    {148,  SyscallDesc("fdatasync", unimplementedFunc)},
    {149,  SyscallDesc("sysctl", unimplementedFunc)},
    {150,  SyscallDesc("mlock", unimplementedFunc)},
    {151,  SyscallDesc("munlock", unimplementedFunc)},
    {152,  SyscallDesc("mlockall", unimplementedFunc)},
    {153,  SyscallDesc("munlockall", unimplementedFunc)},
    {154,  SyscallDesc("sched_setparam", unimplementedFunc)},
    {155,  SyscallDesc("sched_getparam", unimplementedFunc)},
    {156,  SyscallDesc("sched_setscheduler", unimplementedFunc)},
    {157,  SyscallDesc("sched_getscheduler", unimplementedFunc)},
    {158,  SyscallDesc("sched_yield", unimplementedFunc)},
    {159,  SyscallDesc("sched_get_priority_max", unimplementedFunc)},
    {160,  SyscallDesc("sched_get_priority_min", unimplementedFunc)},
    {161,  SyscallDesc("sched_rr_get_interval", unimplementedFunc)},
    {162,  SyscallDesc("nanosleep", ignoreFunc, SyscallDesc::WarnOnce)},
    {163,  SyscallDesc("mremap", mremapFunc<Riscv64Linux>)},
    {164,  SyscallDesc("setresuid", unimplementedFunc)},
    {165,  SyscallDesc("getresuid", unimplementedFunc)},
    {166,  SyscallDesc("unused#166", unimplementedFunc)},
    {167,  SyscallDesc("unused#167", unimplementedFunc)},
    {168,  SyscallDesc("poll", unimplementedFunc)},
    {169,  SyscallDesc("nfsservctl", unimplementedFunc)},
    {170,  SyscallDesc("setresgid", unimplementedFunc)},
    {171,  SyscallDesc("getresgid", unimplementedFunc)},
    {172,  SyscallDesc("prctl", unimplementedFunc)},
    {173,  SyscallDesc("rt_sigreturn", unimplementedFunc)},
    {174,  SyscallDesc("rt_sigaction", ignoreFunc, SyscallDesc::WarnOnce)},
    {175,  SyscallDesc("rt_sigprocmask", ignoreFunc, SyscallDesc::WarnOnce)},
    {176,  SyscallDesc("rt_sigpending", unimplementedFunc)},
    {177,  SyscallDesc("rt_sigtimedwait", unimplementedFunc)},
    {178,  SyscallDesc("rt_sigqueueinfo", ignoreFunc)},
    {179,  SyscallDesc("rt_sigsuspend", unimplementedFunc)},
    {180,  SyscallDesc("pread64", unimplementedFunc)},
    {181,  SyscallDesc("pwrite64", unimplementedFunc)},
    {182,  SyscallDesc("chown", unimplementedFunc)},
    {183,  SyscallDesc("getcwd", getcwdFunc)},
    {184,  SyscallDesc("capget", unimplementedFunc)},
    {185,  SyscallDesc("capset", unimplementedFunc)},
    {186,  SyscallDesc("sigaltstack", unimplementedFunc)},
    {187,  SyscallDesc("sendfile", unimplementedFunc)},
    {188,  SyscallDesc("unused#188", unimplementedFunc)},
    {189,  SyscallDesc("unused#189", unimplementedFunc)},
    {190,  SyscallDesc("vfork", unimplementedFunc)},
    {191,  SyscallDesc("getrlimit", getrlimitFunc<Riscv64Linux>)},
    {192,  SyscallDesc("mmap2", mmapFunc<Riscv64Linux>)},
    {193,  SyscallDesc("truncate64", unimplementedFunc)},
    {194,  SyscallDesc("ftruncate64", ftruncate64Func)},
    {195,  SyscallDesc("stat64", stat64Func<Riscv64Linux>)},
    {196,  SyscallDesc("lstat64", lstat64Func<Riscv64Linux>)},
    {197,  SyscallDesc("fstat64", fstat64Func<Riscv64Linux>)},
    {198,  SyscallDesc("lchown", unimplementedFunc)},
    {199,  SyscallDesc("getuid", getuidFunc)},
    {200,  SyscallDesc("getgid", getgidFunc)},
    {201,  SyscallDesc("geteuid", geteuidFunc)},
    {202,  SyscallDesc("getegid", getegidFunc)},
    {203,  SyscallDesc("setreuid", unimplementedFunc)},
    {204,  SyscallDesc("setregid", unimplementedFunc)},
    {205,  SyscallDesc("getgroups", unimplementedFunc)},
    {206,  SyscallDesc("setgroups", unimplementedFunc)},
    {207,  SyscallDesc("fchown", unimplementedFunc)},
    {208,  SyscallDesc("setresuid", unimplementedFunc)},
    {209,  SyscallDesc("getresuid", unimplementedFunc)},
    {210,  SyscallDesc("setresgid", unimplementedFunc)},
    {211,  SyscallDesc("getresgid", unimplementedFunc)},
    {212,  SyscallDesc("chown", unimplementedFunc)},
    {213,  SyscallDesc("setuid", unimplementedFunc)},
    {214,  SyscallDesc("setgid", unimplementedFunc)},
    {215,  SyscallDesc("setfsuid", unimplementedFunc)},
    {216,  SyscallDesc("setfsgid", unimplementedFunc)},
    {217,  SyscallDesc("getdents64", unimplementedFunc)},
    {218,  SyscallDesc("pivot_root", unimplementedFunc)},
    {219,  SyscallDesc("mincore", unimplementedFunc)},
    {220,  SyscallDesc("madvise", unimplementedFunc)},
    {221,  SyscallDesc("fcntl64", fcntl64Func)},
    {222,  SyscallDesc("unused#222", unimplementedFunc)},
    {223,  SyscallDesc("unknown#223", unimplementedFunc)},
    {224,  SyscallDesc("gettid", unimplementedFunc)},
    {225,  SyscallDesc("readahead", unimplementedFunc)},
    {226,  SyscallDesc("setxattr", unimplementedFunc)},
    {227,  SyscallDesc("lsetxattr", unimplementedFunc)},
    {228,  SyscallDesc("fsetxattr", unimplementedFunc)},
    {229,  SyscallDesc("getxattr", unimplementedFunc)},
    {230,  SyscallDesc("lgetxattr", unimplementedFunc)},
    {231,  SyscallDesc("fgetxattr", unimplementedFunc)},
    {232,  SyscallDesc("listxattr", unimplementedFunc)},
    {233,  SyscallDesc("llistxattr", unimplementedFunc)},
    {234,  SyscallDesc("flistxattr", unimplementedFunc)},
    {235,  SyscallDesc("removexattr", unimplementedFunc)},
    {236,  SyscallDesc("lremovexattr", unimplementedFunc)},
    {237,  SyscallDesc("fremovexattr", unimplementedFunc)},
    {238,  SyscallDesc("tkill", unimplementedFunc)},
    {239,  SyscallDesc("sendfile64", unimplementedFunc)},
    {240,  SyscallDesc("futex", ignoreFunc, SyscallDesc::WarnOnce)},
    {241,  SyscallDesc("sched_setaffinity", unimplementedFunc)},
    {242,  SyscallDesc("sched_getaffinity", unimplementedFunc)},
    {243,  SyscallDesc("io_setup", unimplementedFunc)},
    {244,  SyscallDesc("io_destroy", unimplementedFunc)},
    {245,  SyscallDesc("io_getevents", unimplementedFunc)},
    {246,  SyscallDesc("io_submit", unimplementedFunc)},
    {247,  SyscallDesc("io_cancel", unimplementedFunc)},
    {248,  SyscallDesc("exit_group", exitGroupFunc)},
    {249,  SyscallDesc("lookup_dcookie", unimplementedFunc)},
    {250,  SyscallDesc("epoll_create", unimplementedFunc)},
    {251,  SyscallDesc("epoll_ctl", unimplementedFunc)},
    {252,  SyscallDesc("epoll_wait", unimplementedFunc)},
    {253,  SyscallDesc("remap_file_pages", unimplementedFunc)},
    {254,  SyscallDesc("unused#254", unimplementedFunc)},
    {255,  SyscallDesc("unused#255", unimplementedFunc)},
    {256,  SyscallDesc("set_tid_address", unimplementedFunc)},
    {257,  SyscallDesc("timer_create", unimplementedFunc)},
    {258,  SyscallDesc("timer_settime", unimplementedFunc)},
    {259,  SyscallDesc("timer_gettime", unimplementedFunc)},
    {260,  SyscallDesc("timer_getoverrun", unimplementedFunc)},
    {261,  SyscallDesc("timer_delete", unimplementedFunc)},
    {262,  SyscallDesc("clock_settime", unimplementedFunc)},
    {263,  SyscallDesc("clock_gettime", clock_gettimeFunc<Riscv64Linux>)},
    {264,  SyscallDesc("clock_getres", clock_getresFunc<Riscv64Linux>)},
    {265,  SyscallDesc("clock_nanosleep", unimplementedFunc)},
    {266,  SyscallDesc("statfs64", unimplementedFunc)},
    {267,  SyscallDesc("fstatfs64", unimplementedFunc)},
    {268,  SyscallDesc("tgkill", unimplementedFunc)},
    {269,  SyscallDesc("utimes", unimplementedFunc)},
    {270,  SyscallDesc("arm_fadvise64_64", unimplementedFunc)},
    {271,  SyscallDesc("pciconfig_iobase", unimplementedFunc)},
    {272,  SyscallDesc("pciconfig_read", unimplementedFunc)},
    {273,  SyscallDesc("pciconfig_write", unimplementedFunc)},
    {274,  SyscallDesc("mq_open", unimplementedFunc)},
    {275,  SyscallDesc("mq_unlink", unimplementedFunc)},
    {276,  SyscallDesc("mq_timedsend", unimplementedFunc)},
    {277,  SyscallDesc("mq_timedreceive", unimplementedFunc)},
    {278,  SyscallDesc("mq_notify", unimplementedFunc)},
    {279,  SyscallDesc("mq_getsetattr", unimplementedFunc)},
    {280,  SyscallDesc("waitid", unimplementedFunc)},
    {281,  SyscallDesc("socket", unimplementedFunc)},
    {282,  SyscallDesc("bind", unimplementedFunc)},
    {283,  SyscallDesc("connect", unimplementedFunc)},
    {284,  SyscallDesc("listen", unimplementedFunc)},
    {285,  SyscallDesc("accept", unimplementedFunc)},
    {286,  SyscallDesc("getsockname", unimplementedFunc)},
    {287,  SyscallDesc("getpeername", unimplementedFunc)},
    {288,  SyscallDesc("socketpair", unimplementedFunc)},
    {289,  SyscallDesc("send", unimplementedFunc)},
    {290,  SyscallDesc("sendto", unimplementedFunc)},
    {291,  SyscallDesc("recv", unimplementedFunc)},
    {292,  SyscallDesc("recvfrom", unimplementedFunc)},
    {293,  SyscallDesc("shutdown", unimplementedFunc)},
    {294,  SyscallDesc("setsockopt", unimplementedFunc)},
    {295,  SyscallDesc("getsockopt", unimplementedFunc)},
    {296,  SyscallDesc("sendmsg", unimplementedFunc)},
    {297,  SyscallDesc("rcvmsg", unimplementedFunc)},
    {298,  SyscallDesc("semop", unimplementedFunc)},
    {299,  SyscallDesc("semget", unimplementedFunc)},
    {300,  SyscallDesc("semctl", unimplementedFunc)},
    {301,  SyscallDesc("msgsend", unimplementedFunc)},
    {302,  SyscallDesc("msgrcv", unimplementedFunc)},
    {303,  SyscallDesc("msgget", unimplementedFunc)},
    {304,  SyscallDesc("msgctl", unimplementedFunc)},
    {305,  SyscallDesc("shmat", unimplementedFunc)},
    {306,  SyscallDesc("shmdt", unimplementedFunc)},
    {307,  SyscallDesc("shmget", unimplementedFunc)},
    {308,  SyscallDesc("shmctl", unimplementedFunc)},
    {309,  SyscallDesc("add_key", unimplementedFunc)},
    {310,  SyscallDesc("request_key", unimplementedFunc)},
    {311,  SyscallDesc("keyctl", unimplementedFunc)},
    {312,  SyscallDesc("semtimedop", unimplementedFunc)},
    {313,  SyscallDesc("unused#313", unimplementedFunc)},
    {314,  SyscallDesc("ioprio_set", unimplementedFunc)},
    {315,  SyscallDesc("ioprio_get", unimplementedFunc)},
    {316,  SyscallDesc("inotify_init", unimplementedFunc)},
    {317,  SyscallDesc("inotify_add_watch", unimplementedFunc)},
    {318,  SyscallDesc("inotify_rm_watch", unimplementedFunc)},
    {319,  SyscallDesc("mbind", unimplementedFunc)},
    {320,  SyscallDesc("get_mempolicy", unimplementedFunc)},
    {321,  SyscallDesc("set_mempolicy", unimplementedFunc)},
    {322,  SyscallDesc("openat", unimplementedFunc)},
    {323,  SyscallDesc("mkdirat", unimplementedFunc)},
    {324,  SyscallDesc("mknodat", unimplementedFunc)},
    {325,  SyscallDesc("fchownat", unimplementedFunc)},
    {326,  SyscallDesc("futimesat", unimplementedFunc)},
    {327,  SyscallDesc("fstatat64", unimplementedFunc)},
    {328,  SyscallDesc("unlinkat", unimplementedFunc)},
    {329,  SyscallDesc("renameat", unimplementedFunc)},
    {330,  SyscallDesc("linkat", unimplementedFunc)},
    {331,  SyscallDesc("symlinkat", unimplementedFunc)},
    {332,  SyscallDesc("readlinkat", unimplementedFunc)},
    {333,  SyscallDesc("fchmodat", unimplementedFunc)},
    {334,  SyscallDesc("faccessat", unimplementedFunc)},
    {335,  SyscallDesc("pselect6", unimplementedFunc)},
    {336,  SyscallDesc("ppoll", unimplementedFunc)},
    {337,  SyscallDesc("unshare", unimplementedFunc)},
    {338,  SyscallDesc("set_robust_list", unimplementedFunc)},
    {339,  SyscallDesc("get_robust_list", unimplementedFunc)},
    {340,  SyscallDesc("splice", unimplementedFunc)},
    {341,  SyscallDesc("arm_sync_file_range", unimplementedFunc)},
    {342,  SyscallDesc("tee", unimplementedFunc)},
    {343,  SyscallDesc("vmsplice", unimplementedFunc)},
    {344,  SyscallDesc("move_pages", unimplementedFunc)},
    {345,  SyscallDesc("getcpu", unimplementedFunc)},
    {346,  SyscallDesc("epoll_pwait", unimplementedFunc)},
    {347,  SyscallDesc("sys_kexec_load", unimplementedFunc)},
    {348,  SyscallDesc("sys_utimensat", unimplementedFunc)},
    {349,  SyscallDesc("sys_signalfd", unimplementedFunc)},
    {350,  SyscallDesc("sys_timerfd_create", unimplementedFunc)},
    {351,  SyscallDesc("sys_eventfd", unimplementedFunc)},
    {352,  SyscallDesc("sys_fallocate", unimplementedFunc)},
    {353,  SyscallDesc("sys_timerfd_settime", unimplementedFunc)},
    {354,  SyscallDesc("sys_timerfd_gettime", unimplementedFunc)},
    {355,  SyscallDesc("sys_signalfd4", unimplementedFunc)},
    {356,  SyscallDesc("sys_eventfd2", unimplementedFunc)},
    {357,  SyscallDesc("sys_epoll_create1", unimplementedFunc)},
    {358,  SyscallDesc("sys_dup3", unimplementedFunc)},
    {359,  SyscallDesc("sys_pipe2", unimplementedFunc)},
    {360,  SyscallDesc("sys_inotify_init1", unimplementedFunc)},
    {361,  SyscallDesc("sys_preadv", unimplementedFunc)},
    {362,  SyscallDesc("sys_pwritev", unimplementedFunc)},
    {363,  SyscallDesc("sys_rt_tgsigqueueinfo", unimplementedFunc)},
    {364,  SyscallDesc("sys_perf_event_open", unimplementedFunc)},
    {365,  SyscallDesc("sys_recvmmsg", unimplementedFunc)}
};

std::map<int, SyscallDesc> Riscv64LinuxProcess::syscallDescs = {
    {0,    SyscallDesc("io_setup")},
    {1,    SyscallDesc("io_destroy")},
    {2,    SyscallDesc("io_submit")},
    {3,    SyscallDesc("io_cancel")},
    {4,    SyscallDesc("io_getevents")},
    {5,    SyscallDesc("setxattr")},
    {6,    SyscallDesc("lsetxattr")},
    {7,    SyscallDesc("fsetxattr")},
    {8,    SyscallDesc("getxattr")},
    {9,    SyscallDesc("lgetxattr")},
    {10,   SyscallDesc("fgetxattr")},
    {11,   SyscallDesc("listxattr")},
    {12,   SyscallDesc("llistxattr")},
    {13,   SyscallDesc("flistxattr")},
    {14,   SyscallDesc("removexattr")},
    {15,   SyscallDesc("lremovexattr")},
    {16,   SyscallDesc("fremovexattr")},
    {17,   SyscallDesc("getcwd", getcwdFunc)},
    {18,   SyscallDesc("lookup_dcookie")},
    {19,   SyscallDesc("eventfd2")},
    {20,   SyscallDesc("epoll_create1")},
    {21,   SyscallDesc("epoll_ctl")},
    {22,   SyscallDesc("epoll_pwait")},
    {23,   SyscallDesc("dup", dupFunc)},
    {24,   SyscallDesc("dup3")},
    {25,   SyscallDesc("fcntl", fcntl64Func)},
    {26,   SyscallDesc("inotify_init1")},
    {27,   SyscallDesc("inotify_add_watch")},
    {28,   SyscallDesc("inotify_rm_watch")},
    {29,   SyscallDesc("ioctl", ioctlFunc<Riscv64Linux>)},
    {30,   SyscallDesc("ioprio_get")},
    {31,   SyscallDesc("ioprio_set")},
    {32,   SyscallDesc("flock")},
    {33,   SyscallDesc("mknodat")},
    {34,   SyscallDesc("mkdirat")},
    {35,   SyscallDesc("unlinkat", unlinkatFunc<Riscv64Linux>)},
    {36,   SyscallDesc("symlinkat")},
    {37,   SyscallDesc("linkat")},
    {38,   SyscallDesc("renameat", renameatFunc<Riscv64Linux>)},
    {39,   SyscallDesc("umount2")},
    {40,   SyscallDesc("mount")},
    {41,   SyscallDesc("pivot_root")},
    {42,   SyscallDesc("nfsservctl")},
    {43,   SyscallDesc("statfs", statfsFunc<Riscv64Linux>)},
    {44,   SyscallDesc("fstatfs", fstatfsFunc<Riscv64Linux>)},
    {45,   SyscallDesc("truncate", truncateFunc)},
    {46,   SyscallDesc("ftruncate", ftruncate64Func)},
    {47,   SyscallDesc("fallocate", fallocateFunc)},
    {48,   SyscallDesc("faccessat", faccessatFunc<Riscv64Linux>)},
    {49,   SyscallDesc("chdir")},
    {50,   SyscallDesc("fchdir")},
    {51,   SyscallDesc("chroot")},
    {52,   SyscallDesc("fchmod", fchmodFunc<Riscv64Linux>)},
    {53,   SyscallDesc("fchmodat")},
    {54,   SyscallDesc("fchownat")},
    {55,   SyscallDesc("fchown", fchownFunc)},
    {56,   SyscallDesc("openat", openatFunc<Riscv64Linux>)},
    {57,   SyscallDesc("close", closeFunc)},
    {58,   SyscallDesc("vhangup")},
    {59,   SyscallDesc("pipe2")},
    {60,   SyscallDesc("quotactl")},
    {61,   SyscallDesc("getdents64")},
    {62,   SyscallDesc("lseek", lseekFunc)},
    {63,   SyscallDesc("read", readFunc)},
    {64,   SyscallDesc("write", writeFunc)},
    {66,   SyscallDesc("writev", writevFunc<Riscv64Linux>)},
    {67,   SyscallDesc("pread64")},
    {68,   SyscallDesc("pwrite64", pwrite64Func<Riscv64Linux>)},
    {69,   SyscallDesc("preadv")},
    {70,   SyscallDesc("pwritev")},
    {71,   SyscallDesc("sendfile")},
    {72,   SyscallDesc("pselect6")},
    {73,   SyscallDesc("ppoll")},
    {74,   SyscallDesc("signalfd64")},
    {75,   SyscallDesc("vmsplice")},
    {76,   SyscallDesc("splice")},
    {77,   SyscallDesc("tee")},
    {78,   SyscallDesc("readlinkat", readlinkatFunc<Riscv64Linux>)},
    {79,   SyscallDesc("fstatat", fstatat64Func<Riscv64Linux>)},
    {80,   SyscallDesc("fstat", fstat64Func<Riscv64Linux>)},
    {81,   SyscallDesc("sync")},
    {82,   SyscallDesc("fsync")},
    {83,   SyscallDesc("fdatasync")},
    {84,   SyscallDesc("sync_file_range2")},
    {85,   SyscallDesc("timerfd_create")},
    {86,   SyscallDesc("timerfd_settime")},
    {87,   SyscallDesc("timerfd_gettime")},
    {88,   SyscallDesc("utimensat")},
    {89,   SyscallDesc("acct")},
    {90,   SyscallDesc("capget")},
    {91,   SyscallDesc("capset")},
    {92,   SyscallDesc("personality")},
    {93,   SyscallDesc("exit", exitFunc)},
    {94,   SyscallDesc("exit_group", exitGroupFunc)},
    {95,   SyscallDesc("waitid")},
    {96,   SyscallDesc("set_tid_address", setTidAddressFunc)},
    {97,   SyscallDesc("unshare")},
    {98,   SyscallDesc("futex", futexFunc<Riscv64Linux>)},
    {99,   SyscallDesc("set_robust_list", ignoreFunc, SyscallDesc::WarnOnce)},
    {100,  SyscallDesc("get_robust_list", ignoreFunc, SyscallDesc::WarnOnce)},
    {101,  SyscallDesc("nanosleep")},
    {102,  SyscallDesc("getitimer")},
    {103,  SyscallDesc("setitimer")},
    {104,  SyscallDesc("kexec_load")},
    {105,  SyscallDesc("init_module")},
    {106,  SyscallDesc("delete_module")},
    {107,  SyscallDesc("timer_create")},
    {108,  SyscallDesc("timer_gettime")},
    {109,  SyscallDesc("timer_getoverrun")},
    {110,  SyscallDesc("timer_settime")},
    {111,  SyscallDesc("timer_delete")},
    {112,  SyscallDesc("clock_settime")},
    {113,  SyscallDesc("clock_gettime", clock_gettimeFunc<Riscv64Linux>)},
    {114,  SyscallDesc("clock_getres", clock_getresFunc<Riscv64Linux>)},
    {115,  SyscallDesc("clock_nanosleep")},
    {116,  SyscallDesc("syslog")},
    {117,  SyscallDesc("ptrace")},
    {118,  SyscallDesc("sched_setparam")},
    {119,  SyscallDesc("sched_setscheduler")},
    {120,  SyscallDesc("sched_getscheduler")},
    {121,  SyscallDesc("sched_getparam")},
    {122,  SyscallDesc("sched_setaffinity")},
    {123,  SyscallDesc("sched_getaffinity")},
    {124,  SyscallDesc("sched_yield", ignoreFunc, SyscallDesc::WarnOnce)},
    {125,  SyscallDesc("sched_get_priority_max")},
    {126,  SyscallDesc("sched_get_priority_min")},
    {127,  SyscallDesc("scheD_rr_get_interval")},
    {128,  SyscallDesc("restart_syscall")},
    {129,  SyscallDesc("kill")},
    {130,  SyscallDesc("tkill")},
    {131,  SyscallDesc("tgkill", tgkillFunc<Riscv64Linux>)},
    {132,  SyscallDesc("sigaltstack")},
    {133,  SyscallDesc("rt_sigsuspend", ignoreFunc, SyscallDesc::WarnOnce)},
    {134,  SyscallDesc("rt_sigaction", ignoreFunc, SyscallDesc::WarnOnce)},
    {135,  SyscallDesc("rt_sigprocmask", ignoreFunc, SyscallDesc::WarnOnce)},
    {136,  SyscallDesc("rt_sigpending", ignoreFunc, SyscallDesc::WarnOnce)},
    {137,  SyscallDesc("rt_sigtimedwait", ignoreFunc,SyscallDesc::WarnOnce)},
    {138,  SyscallDesc("rt_sigqueueinfo", ignoreFunc,SyscallDesc::WarnOnce)},
    {139,  SyscallDesc("rt_sigreturn", ignoreFunc, SyscallDesc::WarnOnce)},
    {140,  SyscallDesc("setpriority")},
    {141,  SyscallDesc("getpriority")},
    {142,  SyscallDesc("reboot")},
    {143,  SyscallDesc("setregid")},
    {144,  SyscallDesc("setgid")},
    {145,  SyscallDesc("setreuid")},
    {146,  SyscallDesc("setuid", setuidFunc)},
    {147,  SyscallDesc("setresuid")},
    {148,  SyscallDesc("getresuid")},
    {149,  SyscallDesc("getresgid")},
    {150,  SyscallDesc("getresgid")},
    {151,  SyscallDesc("setfsuid")},
    {152,  SyscallDesc("setfsgid")},
    {153,  SyscallDesc("times", timesFunc<Riscv64Linux>)},
    {154,  SyscallDesc("setpgid", setpgidFunc)},
    {155,  SyscallDesc("getpgid")},
    {156,  SyscallDesc("getsid")},
    {157,  SyscallDesc("setsid")},
    {158,  SyscallDesc("getgroups")},
    {159,  SyscallDesc("setgroups")},
    {160,  SyscallDesc("uname", uname64Func)},
    {161,  SyscallDesc("sethostname")},
    {162,  SyscallDesc("setdomainname")},
    {163,  SyscallDesc("getrlimit", getrlimitFunc<Riscv64Linux>)},
    {164,  SyscallDesc("setrlimit", ignoreFunc)},
    {165,  SyscallDesc("getrusage", getrusageFunc<Riscv64Linux>)},
    {166,  SyscallDesc("umask", umaskFunc)},
    {167,  SyscallDesc("prctl")},
    {168,  SyscallDesc("getcpu")},
    {169,  SyscallDesc("gettimeofday", gettimeofdayFunc<Riscv64Linux>)},
    {170,  SyscallDesc("settimeofday")},
    {171,  SyscallDesc("adjtimex")},
    {172,  SyscallDesc("getpid", getpidFunc)},
    {173,  SyscallDesc("getppid", getppidFunc)},
    {174,  SyscallDesc("getuid", getuidFunc)},
    {175,  SyscallDesc("geteuid", geteuidFunc)},
    {176,  SyscallDesc("getgid", getgidFunc)},
    {177,  SyscallDesc("getegid", getegidFunc)},
    {178,  SyscallDesc("gettid", gettidFunc)},
    {179,  SyscallDesc("sysinfo", sysinfoFunc<Riscv64Linux>)},
    {180,  SyscallDesc("mq_open")},
    {181,  SyscallDesc("mq_unlink")},
    {182,  SyscallDesc("mq_timedsend")},
    {183,  SyscallDesc("mq_timedrecieve")},
    {184,  SyscallDesc("mq_notify")},
    {185,  SyscallDesc("mq_getsetattr")},
    {186,  SyscallDesc("msgget")},
    {187,  SyscallDesc("msgctl")},
    {188,  SyscallDesc("msgrcv")},
    {189,  SyscallDesc("msgsnd")},
    {190,  SyscallDesc("semget")},
    {191,  SyscallDesc("semctl")},
    {192,  SyscallDesc("semtimedop")},
    {193,  SyscallDesc("semop")},
    {194,  SyscallDesc("shmget")},
    {195,  SyscallDesc("shmctl")},
    {196,  SyscallDesc("shmat")},
    {197,  SyscallDesc("shmdt")},
    {198,  SyscallDesc("socket")},
    {199,  SyscallDesc("socketpair")},
    {200,  SyscallDesc("bind")},
    {201,  SyscallDesc("listen")},
    {202,  SyscallDesc("accept")},
    {203,  SyscallDesc("connect")},
    {204,  SyscallDesc("getsockname")},
    {205,  SyscallDesc("getpeername")},
    {206,  SyscallDesc("sendo")},
    {207,  SyscallDesc("recvfrom")},
    {208,  SyscallDesc("setsockopt")},
    {209,  SyscallDesc("getsockopt")},
    {210,  SyscallDesc("shutdown")},
    {211,  SyscallDesc("sendmsg")},
    {212,  SyscallDesc("recvmsg")},
    {213,  SyscallDesc("readahead")},
    {214,  SyscallDesc("brk", brkFunc)},
    {215,  SyscallDesc("munmap", munmapFunc)},
    {216,  SyscallDesc("mremap", mremapFunc<Riscv64Linux>)},
    {217,  SyscallDesc("add_key")},
    {218,  SyscallDesc("request_key")},
    {219,  SyscallDesc("keyctl")},
    {220,  SyscallDesc("clone", cloneFunc<Riscv64Linux>)},
    {221,  SyscallDesc("execve", execveFunc<Riscv64Linux>)},
    {222,  SyscallDesc("mmap", mmapFunc<Riscv64Linux>)},
    {223,  SyscallDesc("fadvise64")},
    {224,  SyscallDesc("swapon")},
    {225,  SyscallDesc("swapoff")},
    {226,  SyscallDesc("mprotect", ignoreFunc)},
    {227,  SyscallDesc("msync", ignoreFunc)},
    {228,  SyscallDesc("mlock", ignoreFunc)},
    {229,  SyscallDesc("munlock", ignoreFunc)},
    {230,  SyscallDesc("mlockall", ignoreFunc)},
    {231,  SyscallDesc("munlockall", ignoreFunc)},
    {232,  SyscallDesc("mincore", ignoreFunc)},
    {233,  SyscallDesc("madvise", ignoreFunc)},
    {234,  SyscallDesc("remap_file_pages")},
    {235,  SyscallDesc("mbind", ignoreFunc)},
    {236,  SyscallDesc("get_mempolicy")},
    {237,  SyscallDesc("set_mempolicy")},
    {238,  SyscallDesc("migrate_pages")},
    {239,  SyscallDesc("move_pages")},
    {240,  SyscallDesc("tgsigqueueinfo")},
    {241,  SyscallDesc("perf_event_open")},
    {242,  SyscallDesc("accept4")},
    {243,  SyscallDesc("recvmmsg")},
    {260,  SyscallDesc("wait4")},
    {261,  SyscallDesc("prlimit64", prlimitFunc<Riscv64Linux>)},
    {262,  SyscallDesc("fanotify_init")},
    {263,  SyscallDesc("fanotify_mark")},
    {264,  SyscallDesc("name_to_handle_at")},
    {265,  SyscallDesc("open_by_handle_at")},
    {266,  SyscallDesc("clock_adjtime")},
    {267,  SyscallDesc("syncfs")},
    {268,  SyscallDesc("setns")},
    {269,  SyscallDesc("sendmmsg")},
    {270,  SyscallDesc("process_vm_ready")},
    {271,  SyscallDesc("process_vm_writev")},
    {272,  SyscallDesc("kcmp")},
    {273,  SyscallDesc("finit_module")},
    {274,  SyscallDesc("sched_setattr")},
    {275,  SyscallDesc("sched_getattr")},
    {276,  SyscallDesc("renameat2")},
    {277,  SyscallDesc("seccomp")},
    {278,  SyscallDesc("getrandom")},
    {279,  SyscallDesc("memfd_create")},
    {280,  SyscallDesc("bpf")},
    {281,  SyscallDesc("execveat")},
    {282,  SyscallDesc("userfaultid")},
    {283,  SyscallDesc("membarrier")},
    {284,  SyscallDesc("mlock2")},
    {285,  SyscallDesc("copy_file_range")},
    {286,  SyscallDesc("preadv2")},
    {287,  SyscallDesc("pwritev2")},
    {1024, SyscallDesc("open", openFunc<Riscv64Linux>)},
    {1025, SyscallDesc("link")},
    {1026, SyscallDesc("unlink", unlinkFunc)},
    {1027, SyscallDesc("mknod")},
    {1028, SyscallDesc("chmod", chmodFunc<Riscv64Linux>)},
    {1029, SyscallDesc("chown", chownFunc)},
    {1030, SyscallDesc("mkdir", mkdirFunc)},
    {1031, SyscallDesc("rmdir")},
    {1032, SyscallDesc("lchown")},
    {1033, SyscallDesc("access", accessFunc)},
    {1034, SyscallDesc("rename", renameFunc)},
    {1035, SyscallDesc("readlink", readlinkFunc)},
    {1036, SyscallDesc("symlink")},
    {1037, SyscallDesc("utimes", utimesFunc<Riscv64Linux>)},
    {1038, SyscallDesc("stat", stat64Func<Riscv64Linux>)},
    {1039, SyscallDesc("lstat", lstat64Func<Riscv64Linux>)},
    {1040, SyscallDesc("pipe", pipeFunc)},
    {1041, SyscallDesc("dup2", dup2Func)},
    {1042, SyscallDesc("epoll_create")},
    {1043, SyscallDesc("inotifiy_init")},
    {1044, SyscallDesc("eventfd")},
    {1045, SyscallDesc("signalfd")},
    {1046, SyscallDesc("sendfile")},
    {1047, SyscallDesc("ftruncate", ftruncate64Func)},
    {1048, SyscallDesc("truncate", truncate64Func)},
    {1049, SyscallDesc("stat", stat64Func<Riscv64Linux>)},
    {1050, SyscallDesc("lstat", lstat64Func<Riscv64Linux>)},
    {1051, SyscallDesc("fstat", fstat64Func<Riscv64Linux>)},
    {1052, SyscallDesc("fcntl", fcntl64Func)},
    {1053, SyscallDesc("fadvise64")},
    {1054, SyscallDesc("newfstatat")},
    {1055, SyscallDesc("fstatfs", fstatfsFunc<Riscv64Linux>)},
    {1056, SyscallDesc("statfs", statfsFunc<Riscv64Linux>)},
    {1057, SyscallDesc("lseek", lseekFunc)},
    {1058, SyscallDesc("mmap", mmapFunc<Riscv64Linux>)},
    {1059, SyscallDesc("alarm")},
    {1060, SyscallDesc("getpgrp")},
    {1061, SyscallDesc("pause")},
    {1062, SyscallDesc("time", timeFunc<Riscv64Linux>)},
    {1063, SyscallDesc("utime")},
    {1064, SyscallDesc("creat")},
    {1065, SyscallDesc("getdents")},
    {1066, SyscallDesc("futimesat")},
    {1067, SyscallDesc("select")},
    {1068, SyscallDesc("poll")},
    {1069, SyscallDesc("epoll_wait")},
    {1070, SyscallDesc("ustat")},
    {1071, SyscallDesc("vfork")},
    {1072, SyscallDesc("oldwait4")},
    {1073, SyscallDesc("recv")},
    {1074, SyscallDesc("send")},
    {1075, SyscallDesc("bdflush")},
    {1076, SyscallDesc("umount")},
    {1077, SyscallDesc("uselib")},
    {1078, SyscallDesc("sysctl")},
    {1079, SyscallDesc("fork")},
    {2011, SyscallDesc("getmainvars")}
};

Riscv32LinuxProcess::Riscv32LinuxProcess(ProcessParams * params,
                                     ObjectFile *objFile,
                                     ObjectFile::Arch _arch)
    : Riscv32Process(params, objFile, _arch)
{}

SyscallDesc*
Riscv32LinuxProcess::getDesc(int callnum)
{
    return syscallDescs.find(callnum) != syscallDescs.end() ?
        &syscallDescs.at(callnum) : nullptr;
}

Riscv64LinuxProcess::Riscv64LinuxProcess(ProcessParams * params,
                                     ObjectFile *objFile,
                                     ObjectFile::Arch _arch)
    : Riscv64Process(params, objFile, _arch)
{}

SyscallDesc*
Riscv64LinuxProcess::getDesc(int callnum)
{
    return syscallDescs.find(callnum) != syscallDescs.end() ?
        &syscallDescs.at(callnum) : nullptr;
}
